### ISSUE TITLE
Getting error when asking a question

### ISSUE THREAD

**Issue by shivaypiece** [Arindam200/gen-ai#1]
<img width="611" alt="image" src="https://github.com/Arindam200/gen-ai/assets/143828586/c31f5926-776d-48f0-bcc2-90af17172b13">

**Comment by Arindam200** [comment]
Oh! My API key got expired! 

I've fixed that now! 

![image](https://github.com/Arindam200/gen-ai/assets/109217591/1bcd9e0a-b05b-41e4-a743-33dbc361f582)


Can you try again?

**Comment by shivaypiece** [comment]
⠋ Generating response...Selected model failed, retrying with gemini-pro...
✖ Error generating content:
fetch is not defined

**Comment by Arindam200** [comment]
Fixed in v0.1.15
